"""Pydantic schemas shared by the API and application services."""
from __future__ import annotations

from avge_engine.schemas.common import (
    BLEND_MODES,
    BOOLEAN_OPS,
    DETAIL_LEVEL,
    GROUP_ACTION,
    PIVOT_MODES,
    PRESET_NAMES,
    StrokeWidthInput,
    ToolResponse,
)
from avge_engine.schemas.document import (
    CloneDocumentRequest,
    CreateDocumentRequest,
    DeleteDocumentRequest,
)
from avge_engine.schemas.operations import (
    BatchRequest,
    CheckpointRequest,
    CritiqueRequest,
    DescribeSceneRequest,
    DocIdBody,
    DocIdLimitBody,
    DuplicateGroupRequest,
    ExportSvgRequest,
    ExtrudeOutlineRequest,
    FindObjectsRequest,
    ManageGroupRequest,
    PreviewRequest,
    ReorderLayerRequest,
    TransformObjectsRequest,
)
from avge_engine.schemas.region import (
    BooleanOpRequest,
    CopyElementRequest,
    CreateCurveRequest,
    CreateEllipseRequest,
    CreateLineRequest,
    CreateRectRequest,
    CreateRegionRequest,
    DeleteRegionRequest,
    EditRegionRequest,
)

__all__ = [
    "BLEND_MODES",
    "BOOLEAN_OPS",
    "DETAIL_LEVEL",
    "GROUP_ACTION",
    "PIVOT_MODES",
    "PRESET_NAMES",
    "StrokeWidthInput",
    "BatchRequest",
    "BooleanOpRequest",
    "CheckpointRequest",
    "CloneDocumentRequest",
    "CopyElementRequest",
    "CreateCurveRequest",
    "CreateDocumentRequest",
    "CreateEllipseRequest",
    "CreateLineRequest",
    "CreateRectRequest",
    "CreateRegionRequest",
    "CritiqueRequest",
    "DeleteDocumentRequest",
    "DeleteRegionRequest",
    "DescribeSceneRequest",
    "DocIdBody",
    "DocIdLimitBody",
    "DuplicateGroupRequest",
    "EditRegionRequest",
    "ExportSvgRequest",
    "ExtrudeOutlineRequest",
    "FindObjectsRequest",
    "ManageGroupRequest",
    "PreviewRequest",
    "ReorderLayerRequest",
    "ToolResponse",
    "TransformObjectsRequest",
]
